In [36]:
import numpy as np
import scipy as sp
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.colors import LogNorm
import scipy.stats as stats
from matplotlib import gridspec
import aplpy as apl #The Astronomy Plotting Library for python
import astropy
from astropy.stats import sigma_clip
from astropy.modeling import functional_models, models, fitting
import astropy.units as U
from astropy.coordinates import ICRS, Galactic, FK4, FK5, Angle, Latitude, Longitude
import astropy.constants as C
from astropy import wcs
import astropy.io.fits as fits
from astropy.io import ascii
import astropy.coordinates as coord
from astropy.coordinates import SkyCoord
from astropy.stats import signal_to_noise_oir_ccd as SNRas
#import spectral_cube as SC
#from spectral_cube import SpectralCube as sc
from astropy.wcs import WCS
matplotlib.use('Agg')
import matplotlib.cm as cm
#import astrometry as ast
import pyfits
import requests
import json
import os
from sklearn import datasets, linear_model
from scipy.optimize import curve_fit
import numpy.ma as ma
from astropy.table import Table, Column
import pyextract
import sewpy
import pandas as pd
from astropy import units as u

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:25: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "/home/lynge/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/lynge/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/lynge/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 477,

In [37]:
sta1_RA_WORLD = SkyCoord('18:45:08.692 -62:22:19.00', unit=(u.hourangle, u.deg)).ra.degree #UCAC3 86-422902
sta1_DEC_WORLD = SkyCoord('18:45:08.692 -62:22:19.00', unit=(u.hourangle, u.deg)).dec.degree

sta2_RA_WORLD = SkyCoord('18:45:03.546 -62:19:21.20', unit=(u.hourangle, u.deg)).ra.degree #TYC 8438-1960-1
sta2_DEC_WORLD = SkyCoord('18:45:03.546 -62:19:21.20', unit=(u.hourangle, u.deg)).dec.degree

sta3_RA_WORLD = float('nan') #SkyCoord('18:44:36.00000 -62:24:03.0000', unit=(u.hourangle, u.deg)).ra.degree #TYC 8438-1960-1
sta3_DEC_WORLD = float('nan') #SkyCoord('18:44:36.00000 -62:24:03.0000', unit=(u.hourangle, u.deg)).dec.degree

sky_RA_WORLD = SkyCoord('18:45:10 -62:22:42', unit=(u.hourangle, u.deg)).ra.degree #Random patch of sky
sky_DEC_WORLD = SkyCoord('18:45:10 -62:22:42', unit=(u.hourangle, u.deg)).dec.degree

k_g = 0.16 #https://www.eso.org/sci/observing/tools/Extinction.html
k_r = 0.08
k_i = 0.02
k_z = 0.01

mag_refsta1_g = 13.291
mag_refsta1_r = 12.843
mag_refsta1_i = 12.668
mag_refsta1_z = 12.593

mag_refsta2_g = 11.689
mag_refsta2_r = 11.491
mag_refsta2_i = 11.465
mag_refsta2_z = 11.500

mag_refsta3_g = 10.166
mag_refsta3_r = 10.229
mag_refsta3_i = 10.347
mag_refsta3_z = 10.456

mag_refsta4_g = 11.861
mag_refsta4_r = 11.562
mag_refsta4_i = 11.460
mag_refsta4_z = 11.430

#refsta1_RA = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).ra.degree #P525_E_21_10_17
#refsta1_DEC = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).dec.degree 

#refsta2_RA = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).ra.degree #P525_E_21_10_17
#refsta2_DEC = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).dec.degree 

refsta1_RA = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).ra.degree #P525_E_21_10_17
refsta1_DEC = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).dec.degree 

refsta2_RA = SkyCoord('00:55:09.9097 +00:43:12.906', unit=(u.hourangle, u.deg)).ra.degree #SA092_342_27_11_17
refsta2_DEC = SkyCoord('00:55:09.9097 +00:43:12.906', unit=(u.hourangle, u.deg)).dec.degree 

refsta3_RA = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).ra.degree #P525-E
refsta3_DEC = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).dec.degree

refsta4_RA = float('nan') #SkyCoord('01:54:38 00:43:01', unit=(u.hourangle, u.deg)).ra.degree #SA093_317
refsta4_DEC = float('nan') #SkyCoord('01:54:38 00:43:01', unit=(u.hourangle, u.deg)).dec.degree 

In [38]:
QUASAR1_g = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/g/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/g/')]

QUASAR2_g = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/')]

refsta1_g = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/g/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/g/')]

refsta2_g = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/')]


In [39]:
QUASAR1_r = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/')]

QUASAR2_r = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/r/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/r/')]

refsta1_r = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/')]

refsta2_r = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/')]



In [40]:
QUASAR1_i = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/')]

QUASAR2_i = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/i/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/i/')]

refsta1_i = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/')]

refsta2_i = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/')]



In [41]:
QUASAR1_z = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/')]

QUASAR2_z = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/')]

refsta1_z = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/')]

refsta2_z = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/')]


In [42]:
def dist(mid,end):
    return np.sqrt((mid[0] - end[0])**2 + (mid[1] - end[1])**2)

In [43]:
def flux_cal(A_mag,B_mag,B_flux):
    '''Flux of A found through magnitude and flux of B'''
    return B_flux*10**((B_mag-A_mag)/2.5)

In [44]:
def Basic(quasar,header):
    '''Provides a basic list of neccesities from the fits header file for use in the later \
    flux determination, it does not serve an individual purpose beyound that'''
    AGNdata = quasar #np.rot90(np.rot90(np.fliplr(quasar)))
    #header = data[0].header
    #print header
    RAstd = header['CRVAL1']
    DECstd = header['CRVAL2']
    #print RAstd, DECstd
    pixspa = header['PIXSCALE']/(3600.)
    #print pixspa
    RAstdpix = header['CRPIX1']
    DECstdpix = header['CRPIX2']
    exptime = 10 # header['EXPTIME']
    return header,AGNdata,RAstd,DECstd,pixspa,RAstdpix,DECstdpix,exptime

In [45]:
def curve(quasar,header,w,center,apparature):
    '''Determines the FLUX of the stellar object given the the numpy array of the image, \
    the header of the fits file, the astropy coordinate representation, \
    the object position and the apparature of interest'''
    header,AGNdata,RAstd,DECstd,pixspa,RAstdpix,DECstdpix,exptime = Basic(quasar,header)
    #AGNdata = np.swapaxes(AGNdata,0,1)
    y, x = np.ogrid[0:header['NAXIS1'],0:header['NAXIS1']]
    #w = np.swapaxes(w,0,1)
    #F_AGN = np.zeros((512,512,3)) #((int(2*apparature/pixspa)+1,int(2*apparature/pixspa)+1,3))
    #print center
    x1 = w.all_world2pix(center[0],center[1],0)
    x1,y1 = (x1[0]),(x1[1])
    try:
        mask = ((y-y1)**2 + (x-x1)**2) > (apparature/float(pixspa))**2
        AGNdata[mask] = float(0)
        mask = AGNdata == 0.
        rows = np.flatnonzero((~mask).sum(axis=1))
        cols = np.flatnonzero((~mask).sum(axis=0))
        AGNdata = AGNdata[rows.min():rows.max()+1, cols.min():cols.max()+1]
        #print apparature/float(pixspa)
    except:
        AGNdata = np.array([[float('nan'),float('nan')],[float('nan'),float('nan')]])
    #if np.sum(AGNdata) < 500:
    #    AGNdata = np.array([[float('nan'),float('nan')],[float('nan'),float('nan')]])
    return AGNdata/float(exptime), x1, y1


In [46]:
def comp1(qua,sta):
    '''Code to determine the relation between the AGN and the Stellar flux as determined by either me \
    or by the SExtractor program respectively'''
    comp = qua/sta
    return comp

In [47]:
def SNR(data1,data2,header,ap1,ap2):
    npix1 = np.pi*ap1**2/((header['PIXSCALE']/3600.)**2)
    npix2 = np.pi*ap2**2/((header['PIXSCALE']/3600.)**2)
    #data2_1 = ((data2-data1)/npix2)*npix1
    data1_2 = data1/10.
    data2_2 = data2/10.
    return SNRas(10.,data1_2,abs(data2_2),0,header['RON'],npix1,gain=header['GAIN'])

In [48]:
def SXtable(quas,aperture):
    header = pyfits.getheader(quas)
    phot_app = aperture*3600/header['PIXSCALE']
    np.set_printoptions(threshold=np.inf)
    sew = sewpy.SEW(params=['XMODEL_WORLD', 'YMODEL_WORLD', 'X2MODEL_WORLD', 'Y2MODEL_WORLD', 
                            'XMODEL_IMAGE', 'YMODEL_IMAGE', 'FLUX_RADIUS(1)', 'FLUX_APER','ELLIPTICITY'],
                    config={"DETECT_THRESH":5, 'DETECT_MINAREA':20, 'DETECT_MAXAREA':30000, 
                            "PHOT_FLUXFRAC":"0.5", 'PHOT_APERTURES':2*phot_app, 
                            'PIXEL_SCALE':header['PIXSCALE']}
                    , sexpath='/usr/bin/sextractor')
    out = sew(quas)
    return out

In [49]:
def flux(quas,aperture,main_RA_WORLD,main_DEC_WORLD):
    header = pyfits.getheader(quas)
    RAmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,1)[0]
    DECmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,1)[1]
    output = float('nan')
    if 15 < RAmain < header['NAXIS1'] - 15 and 15 < DECmain < header['NAXIS2'] - 15: 
        out = SXtable(quas,aperture)
        #print out['table']['XMODEL_IMAGE']
        #print RAmain
        RAmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,0)[0]
        DECmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,0)[1]
        #print out['table']['XMODEL_IMAGE'], out['table']['YMODEL_IMAGE']
        #print RAmain, DECmain

        for j in range(len(out['table']['XMODEL_IMAGE'])):
            #output['time'][i] = header['MJD-OBS']
            if RAmain - 20. < out['table']['XMODEL_IMAGE'][j] <  RAmain + 20. and \
            DECmain - 20. < out['table']['YMODEL_IMAGE'][j] < DECmain + 20.:
                #print 'YES'
                output = out['table']['FLUX_APER'][j]
                break
    else:
        output = float('nan')
        #print 'Done'
    return output


In [50]:
def findmag(start,compare1,RA_star,DEC_star,RA_com,DEC_com,mag_com,AIR_EXTINCTION):
    aperture1 = 0.0005
    #201.5441,-8.8601
    com_flu = []
    com_AIRMASS = []
    com_EXPTIME = []
    star_flu = []
    star_AIRMASS = []
    star_EXPTIME = []
    for i in range(len(compare1)):
        print 'Frame nr. ', i, compare1[i]
        header = pyfits.getheader(compare1[i])
        a1 = flux(compare1[i],2*aperture1,RA_com,DEC_com)/header['EXPTIME']
        if a1 > 0:
            #print a1
            com_flu.append(a1), com_AIRMASS.append(header['AIRMASS']*AIR_EXTINCTION), com_EXPTIME.append(header['EXPTIME'])
        else:
            print a1
            com_flu.append(float('nan')), com_AIRMASS.append(float('nan')), com_EXPTIME.append(header['EXPTIME'])
        #plt.figure(figsize=(3,3))
        #plt.imshow(a1,cmap='hot')
        #plt.colorbar()
    for i in range(len(start)):
        print 'Frame nr. ', i, start[i]
        header = pyfits.getheader(start[i])
        a1 = flux(start[i],2*aperture1,RA_star,DEC_star)/header['EXPTIME']
        if a1 > 0:
            #print a1
            star_flu.append(a1), star_AIRMASS.append(header['AIRMASS']*AIR_EXTINCTION), star_EXPTIME.append(header['EXPTIME'])
        else:
            star_flu.append(float('nan')), star_AIRMASS.append(float('nan')), star_EXPTIME.append(header['EXPTIME'])
        #plt.figure(figsize=(3,3))
        #plt.imshow(a1,cmap='hot')
        #plt.colorbar()
    com_flu = np.array(com_flu)
    com_AIRMASS = np.array(com_AIRMASS)
    com_EXPTIME = np.array(com_EXPTIME)
    star_flu = np.array(star_flu)
    star_AIRMASS = np.array(star_AIRMASS)
    star_EXPTIME = np.array(star_EXPTIME)
    com_flu = com_flu/com_EXPTIME
    star_flu = star_flu/star_EXPTIME
    com_flux = np.nanmean(com_flu)
    com_AIRMASS_num = np.nanmean(com_AIRMASS)
    star_AIRMASS_num = np.nanmean(star_AIRMASS)
    mag = -(star_AIRMASS_num-com_AIRMASS_num) + mag_com - 2.5*np.log10(star_flu/float(com_flux))
    #print mag
    return mag

In [51]:
com1_1 = findmag(QUASAR1_g,refsta1_g,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_g,k_g)
com2_1 = findmag(QUASAR1_g,refsta1_g,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_g,k_g)
com3_1 = findmag(QUASAR1_g,refsta1_g,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_g,k_g)

com1_2 = findmag(QUASAR2_g,refsta2_g,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_g,k_g)
com2_2 = findmag(QUASAR2_g,refsta2_g,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_g,k_g)
com3_2 = findmag(QUASAR2_g,refsta2_g,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_g,k_g)



Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/g/IMG2017292URh017.fits
INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:45: RuntimeWarning: Mean of empty slice


Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URh002.fits
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URh003.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URh006.fits
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URh007.fits
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URs004.fits
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URs005.fits
nan
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URs008.fits
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URs009.fits
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/IMG2017329URs026.fits
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/IMG2017329URs027.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-

In [52]:
print 'g-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

g-filter
Star 1
[14.91794088 14.90546191 14.91526242] [14.59809867 14.59377917 14.58119012]
14.751955526986748 0.16105744595055949
Star 2
[15.03336858 15.01955942 15.0133688 ] [14.65676032 14.65346097 14.6607864 ]
14.839550750705678 0.18265615598090065
Star 3
[nan nan nan] [nan nan nan]
nan nan


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: Mean of empty slice
  if sys.path[0] == '':
/home/lynge/anaconda2/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:1434: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)


In [53]:
com1_1 = findmag(QUASAR1_r,refsta1_r,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_r,k_r)
com2_1 = findmag(QUASAR1_r,refsta1_r,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_r,k_r)
com3_1 = findmag(QUASAR1_r,refsta1_r,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_r,k_r)

com1_2 = findmag(QUASAR2_r,refsta2_r,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_r,k_r)
com2_2 = findmag(QUASAR2_r,refsta2_r,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_r,k_r)
com3_2 = findmag(QUASAR2_r,refsta2_r,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_r,k_r)



Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh017.fits
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh018.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh021.fits
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh022.fits
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs019.fits
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs020.fits
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs023.fits
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs024.fits
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/IMG2017292BRs091.fits
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/IMG2017292BRs092.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/IMG2017292BRs093.fi

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:45: RuntimeWarning: Mean of empty slice


Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRh002.fits
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRh003.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRh006.fits
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRh007.fits
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRs004.fits
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRs005.fits
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRs008.fits
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRs009.fits
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/r/IMG2017329BRs026.fits
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/r/IMG2017329BRs027.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F

In [54]:
print 'r-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

r-filter
Star 1
[14.10531486 14.10574111 14.09128981] [13.94351572 13.92414817 13.9046583 ]
14.012444660754033 0.0891730801061837
Star 2
[14.49954209 14.48813331 14.48138856] [14.27024397 14.26731204 14.25602844]
14.37710806950632 0.11278777790784056
Star 3
[nan nan nan] [nan nan nan]
nan nan


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: Mean of empty slice
  if sys.path[0] == '':


In [55]:
com1_1 = findmag(QUASAR1_i,refsta1_i,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_i,k_i)
com2_1 = findmag(QUASAR1_i,refsta1_i,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_i,k_i)
com3_1 = findmag(QUASAR1_i,refsta1_i,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_i,k_i)

com1_2 = findmag(QUASAR2_i,refsta2_i,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_i,k_i)
com2_2 = findmag(QUASAR2_i,refsta2_i,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_i,k_i)
com3_2 = findmag(QUASAR2_i,refsta2_i,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_i,k_i)



Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh017.fits
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh018.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh021.fits
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh022.fits
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs019.fits
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs020.fits
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs023.fits
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs024.fits
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/IMG2017292ULs091.fits
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/IMG2017292ULs092.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/IMG2017292ULs093.fi

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:45: RuntimeWarning: Mean of empty slice


Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULh003.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULh006.fits
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULh007.fits
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULs004.fits
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULs005.fits
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULs008.fits
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULs009.fits
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/i/IMG2017329ULs026.fits
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/i/IMG2017329ULs027.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/i/IMG2017329ULs028.fits
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_3

In [56]:
print 'i-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

i-filter
Star 1
[13.9143557  13.89775081 13.89145466] [13.49587857 13.48627321 13.47604444]
13.693626231927198 0.20775212929371373
Star 2
[14.45476637 14.41949135 14.42119635] [14.06775685 14.08121064 14.0790107 ]
14.253905377326289 0.17833162754997586
Star 3
[nan nan nan] [nan nan nan]
nan nan


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: Mean of empty slice
  if sys.path[0] == '':


In [57]:
com1_1 = findmag(QUASAR1_z,refsta1_z,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_z,k_z)
com2_1 = findmag(QUASAR1_z,refsta1_z,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_z,k_z)
com3_1 = findmag(QUASAR1_z,refsta1_z,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_z,k_z)

com1_2 = findmag(QUASAR2_z,refsta2_z,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_z,k_z)
com2_2 = findmag(QUASAR2_z,refsta2_z,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_z,k_z)
com3_2 = findmag(QUASAR2_z,refsta2_z,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_z,k_z)



Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh017.fits
nan
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh018.fits
nan
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh021.fits
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh022.fits
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs019.fits
nan
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs020.fits
nan
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs023.fits
nan
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs024.fits
nan
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/IMG2017292BLs091.fits
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/IMG2017292BLs092.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:45: RuntimeWarning: Mean of empty slice


Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLh002.fits
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLh003.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLh006.fits
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLh007.fits
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLs004.fits
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLs005.fits
nan
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLs008.fits
nan
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLs009.fits
nan
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/IMG2017329BLs026.fits
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/IMG2017329BLs027.fits
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibratio

In [58]:
print 'z-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

z-filter
Star 1
[13.30775944 13.28033792 13.28959403] [13.0555038  13.01589221 13.01704526]
13.161022108269606 0.13242921269046273
Star 2
[13.94203131 13.93200871 13.91175858] [13.57991082 13.56662618 13.5789009 ]
13.751872750353238 0.17700243824450007
Star 3
[nan nan nan] [nan nan nan]
nan nan


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: Mean of empty slice
  if sys.path[0] == '':


In [59]:
HD101274_1 = findmag(NGC3783_r,P_r,sta1_RA_WORLD,sta1_DEC_WORLD,r_P_RA,r_P_DEC,P_mag_r,k_r)
Tyc_22_1 = findmag(NGC3783_r,P_r,sta2_RA_WORLD,sta2_DEC_WORLD,r_P_RA,r_P_DEC,P_mag_r,k_r)
Tyc_529_1 = findmag(NGC3783_r,P_r,sta3_RA_WORLD,sta3_DEC_WORLD,r_P_RA,r_P_DEC,P_mag_r,k_r)




NameError: name 'NGC3783_r' is not defined

In [ ]:
print 'r-filter'
print HD101274_1
print np.mean(HD101274_1,), np.std(HD101274_1)

print Tyc_22_1
print np.mean(Tyc_22_1), np.std(Tyc_22_1)

print Tyc_529_1
print np.mean(Tyc_529_1), np.std(Tyc_529_1)

In [ ]:
HD101274_1 = findmag(NGC3783_i,P_i,sta1_RA_WORLD,sta1_DEC_WORLD,i_P_RA,i_P_DEC,P_mag_i,k_i)
Tyc_22_1 = findmag(NGC3783_i,P_i,sta2_RA_WORLD,sta2_DEC_WORLD,i_P_RA,i_P_DEC,P_mag_i,k_i)
Tyc_529_1 = findmag(NGC3783_i,P_i,sta3_RA_WORLD,sta3_DEC_WORLD,i_P_RA,i_P_DEC,P_mag_i,k_i)




In [ ]:
print 'i-filter'
print HD101274_1
print np.mean(HD101274_1,), np.std(HD101274_1)

print Tyc_22_1
print np.mean(Tyc_22_1), np.std(Tyc_22_1)

print Tyc_529_1
print np.mean(Tyc_529_1), np.std(Tyc_529_1)

In [ ]:
sta2_RA_WORLD = 174.82083333
sta2_DEC_WORLD = -37.76194444

HD101274_1 = findmag(NGC3783_z,P_z,sta1_RA_WORLD,sta1_DEC_WORLD,z_P_RA,z_P_DEC,P_mag_z,k_z)
Tyc_22_1 = findmag(NGC3783_z,P_z,sta2_RA_WORLD,sta2_DEC_WORLD,z_P_RA,z_P_DEC,P_mag_z,k_z)
Tyc_529_1 = findmag(NGC3783_z,P_z,sta3_RA_WORLD,sta3_DEC_WORLD,z_P_RA,z_P_DEC,P_mag_z,k_z)




In [ ]:
print 'z-filter'
print HD101274_1
print np.nanmean(HD101274_1,), np.nanstd(HD101274_1)

print Tyc_22_1
print np.nanmean(Tyc_22_1), np.nanstd(Tyc_22_1)

print Tyc_529_1
print np.nanmean(Tyc_529_1), np.nanstd(Tyc_529_1)