In [1]:
import numpy as np
import scipy as sp
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.colors import LogNorm
import scipy.stats as stats
from matplotlib import gridspec
import aplpy as apl #The Astronomy Plotting Library for python
import astropy
from astropy.stats import sigma_clip
from astropy.modeling import functional_models, models, fitting
import astropy.units as U
from astropy.coordinates import ICRS, Galactic, FK4, FK5, Angle, Latitude, Longitude
import astropy.constants as C
from astropy import wcs
import astropy.io.fits as fits
from astropy.io import ascii
import astropy.coordinates as coord
from astropy.coordinates import SkyCoord
from astropy.stats import signal_to_noise_oir_ccd as SNRas
#import spectral_cube as SC
#from spectral_cube import SpectralCube as sc
from astropy.wcs import WCS
matplotlib.use('Agg')
import matplotlib.cm as cm
#import astrometry as ast
import pyfits
import requests
import json
import os
from sklearn import datasets, linear_model
from scipy.optimize import curve_fit
import numpy.ma as ma
from astropy.table import Table, Column
import pyextract
import sewpy
import pandas as pd
from astropy import units as u

/home/lynge/anaconda2/lib/python2.7/site-packages/matplotlib/cbook/deprecation.py:106: MatplotlibDeprecationWarning: The mpl_toolkits.axes_grid module was deprecated in version 2.1. Use mpl_toolkits.axes_grid1 and mpl_toolkits.axisartist provies the same functionality instead.
  warnings.warn(message, mplDeprecation, stacklevel=1)
/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:25: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "/home/lynge/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/lynge/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lynge/anaconda2

In [2]:
sta1_RA_WORLD = SkyCoord('18:45:08.692 -62:22:19.00', unit=(u.hourangle, u.deg)).ra.degree #UCAC3 86-422902
sta1_DEC_WORLD = SkyCoord('18:45:08.692 -62:22:19.00', unit=(u.hourangle, u.deg)).dec.degree

sta2_RA_WORLD = SkyCoord('18:45:03.546 -62:19:21.20', unit=(u.hourangle, u.deg)).ra.degree #TYC 8438-1960-1
sta2_DEC_WORLD = SkyCoord('18:45:03.546 -62:19:21.20', unit=(u.hourangle, u.deg)).dec.degree

sta3_RA_WORLD = float('nan') #SkyCoord('18:44:36.00000 -62:24:03.0000', unit=(u.hourangle, u.deg)).ra.degree #TYC 8438-1960-1
sta3_DEC_WORLD = float('nan') #SkyCoord('18:44:36.00000 -62:24:03.0000', unit=(u.hourangle, u.deg)).dec.degree

sky_RA_WORLD = SkyCoord('18:45:10 -62:22:42', unit=(u.hourangle, u.deg)).ra.degree #Random patch of sky
sky_DEC_WORLD = SkyCoord('18:45:10 -62:22:42', unit=(u.hourangle, u.deg)).dec.degree

k_g = 0.16
k_r = 0.08
k_i = 0.02
k_z = 0.01

mag_refsta1_g = 13.291
mag_refsta1_r = 12.843
mag_refsta1_i = 12.668
mag_refsta1_z = 12.593

mag_refsta2_g = 11.689
mag_refsta2_r = 11.491
mag_refsta2_i = 11.465
mag_refsta2_z = 11.500

refsta1_RA = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).ra.degree #P525_E_21_10_17
refsta1_DEC = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).dec.degree 

refsta2_RA = SkyCoord('00:55:09.9097 +00:43:12.906', unit=(u.hourangle, u.deg)).ra.degree #SA092_342_27_11_17
refsta2_DEC = SkyCoord('00:55:09.9097 +00:43:12.906', unit=(u.hourangle, u.deg)).dec.degree 

In [3]:
QUASAR1_g = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/g/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/g/')]

QUASAR2_g = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/')]

refsta1_g = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/g/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/g/')]

refsta2_g = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/')]

In [4]:
QUASAR1_r = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/')]

QUASAR2_r = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/r/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/r/')]

refsta1_r = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/')]

refsta2_r = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/')]

In [5]:
QUASAR1_i = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/')]

QUASAR2_i = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/i/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/i/')]

refsta1_i = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/')]

refsta2_i = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/')]

In [6]:
QUASAR1_z = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/')]

QUASAR2_z = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/')]

refsta1_z = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/')]

refsta2_z = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/')]

print QUASAR2_z

['/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/IMG2017329BLs026.fits', '/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/IMG2017329BLs027.fits', '/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/IMG2017329BLs028.fits']


In [7]:
def dist(mid,end):
    return np.sqrt((mid[0] - end[0])**2 + (mid[1] - end[1])**2)

In [8]:
def flux_cal(A_mag,B_mag,B_flux):
    '''Flux of A found through magnitude and flux of B'''
    return B_flux*10**((B_mag-A_mag)/2.5)

In [9]:
def Basic(quasar,header):
    '''Provides a basic list of neccesities from the fits header file for use in the later \
    flux determination, it does not serve an individual purpose beyound that'''
    AGNdata = quasar #np.rot90(np.rot90(np.fliplr(quasar)))
    #header = data[0].header
    #print header
    RAstd = header['CRVAL1']
    DECstd = header['CRVAL2']
    #print RAstd, DECstd
    pixspa = header['PIXSCALE']/(3600.)
    #print pixspa
    RAstdpix = header['CRPIX1']
    DECstdpix = header['CRPIX2']
    exptime = 10 # header['EXPTIME']
    return header,AGNdata,RAstd,DECstd,pixspa,RAstdpix,DECstdpix,exptime

In [10]:
def curve(quasar,header,w,center,apparature):
    '''Determines the FLUX of the stellar object given the the numpy array of the image, \
    the header of the fits file, the astropy coordinate representation, \
    the object position and the apparature of interest'''
    header,AGNdata,RAstd,DECstd,pixspa,RAstdpix,DECstdpix,exptime = Basic(quasar,header)
    #AGNdata = np.swapaxes(AGNdata,0,1)
    y, x = np.ogrid[0:header['NAXIS1'],0:header['NAXIS1']]
    #w = np.swapaxes(w,0,1)
    #F_AGN = np.zeros((512,512,3)) #((int(2*apparature/pixspa)+1,int(2*apparature/pixspa)+1,3))
    #print center
    x1 = w.all_world2pix(center[0],center[1],0)
    x1,y1 = (x1[0]),(x1[1])
    try:
        mask = ((y-y1)**2 + (x-x1)**2) > (apparature/float(pixspa))**2
        AGNdata[mask] = float(0)
        mask = AGNdata == 0.
        rows = np.flatnonzero((~mask).sum(axis=1))
        cols = np.flatnonzero((~mask).sum(axis=0))
        AGNdata = AGNdata[rows.min():rows.max()+1, cols.min():cols.max()+1]
        #print apparature/float(pixspa)
    except:
        AGNdata = np.array([[float('nan'),float('nan')],[float('nan'),float('nan')]])
    #if np.sum(AGNdata) < 500:
    #    AGNdata = np.array([[float('nan'),float('nan')],[float('nan'),float('nan')]])
    return AGNdata/float(exptime), x1, y1


In [11]:
def comp1(qua,sta):
    '''Code to determine the relation between the AGN and the Stellar flux as determined by either me \
    or by the SExtractor program respectively'''
    comp = qua/sta
    return comp

In [12]:
def SNR(data1,data2,header,ap1,ap2):
    npix1 = np.pi*ap1**2/((header['PIXSCALE']/3600.)**2)
    npix2 = np.pi*ap2**2/((header['PIXSCALE']/3600.)**2)
    #data2_1 = ((data2-data1)/npix2)*npix1
    data1_2 = data1/10.
    data2_2 = data2/10.
    return SNRas(10.,data1_2,abs(data2_2),0,header['RON'],npix1,gain=header['GAIN'])

In [13]:
def SXtable(quas,aperture):
    header = pyfits.getheader(quas)
    phot_app = aperture*3600/header['PIXSCALE']
    np.set_printoptions(threshold=np.inf)
    sew = sewpy.SEW(params=['XMODEL_WORLD', 'YMODEL_WORLD', 'X2MODEL_WORLD', 'Y2MODEL_WORLD', 
                            'XMODEL_IMAGE', 'YMODEL_IMAGE', 'FLUX_RADIUS(1)', 'FLUX_APER','ELLIPTICITY'],
                    config={"DETECT_THRESH":10, 'DETECT_MINAREA':20, 'DETECT_MAXAREA':30000, 
                            "PHOT_FLUXFRAC":"0.5", 'PHOT_APERTURES':2*phot_app, 
                            'PIXEL_SCALE':header['PIXSCALE']}
                    , sexpath='/usr/bin/sextractor')
    out = sew(quas)
    return out

In [14]:
def flux(quas,aperture,main_RA_WORLD,main_DEC_WORLD):
    header = pyfits.getheader(quas)
    RAmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,1)[0]
    DECmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,1)[1]
    output = float('nan')
    if 15 < RAmain < header['NAXIS1'] - 15 and 15 < DECmain < header['NAXIS2'] - 15: 
        out = SXtable(quas,aperture)
        #print out['table']['XMODEL_IMAGE']
        #print RAmain
        RAmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,0)[0]
        DECmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,0)[1]
        #print out['table']['XMODEL_IMAGE'], out['table']['YMODEL_IMAGE']
        #print RAmain, DECmain

        for j in range(len(out['table']['XMODEL_IMAGE'])):
            #output['time'][i] = header['MJD-OBS']
            if RAmain - 20. < out['table']['XMODEL_IMAGE'][j] <  RAmain + 20. and \
            DECmain - 20. < out['table']['YMODEL_IMAGE'][j] < DECmain + 20.:
                #print 'YES'
                output = out['table']['FLUX_APER'][j]
                break
    else:
        output = float('nan')
        #print 'Done'
    return output


In [15]:
def findmag(start,compare1,RA_star,DEC_star,RA_com,DEC_com,mag_com,AIR_EXTINCTION):
    print mag_com
    aperture1 = 0.001
    #201.5441,-8.8601
    com_flu = []
    com_AIRMASS = []
    com_EXPTIME = []
    star_flu = []
    star_AIRMASS = []
    star_EXPTIME = []
    for i in range(len(compare1)):
        print 'Frame nr. ', i, compare1[i]
        header = pyfits.getheader(compare1[i])
        a1 = flux(compare1[i],2*aperture1,RA_com,DEC_com)/float(header['EXPTIME'])
        print header['EXPTIME']
        if a1 > 0:
            #print a1
            com_flu.append(a1), com_AIRMASS.append(header['AIRMASS']*AIR_EXTINCTION), com_EXPTIME.append(header['EXPTIME'])
        else:
            print a1
            com_flu.append(float('nan')), com_AIRMASS.append(float('nan')), com_EXPTIME.append(header['EXPTIME'])
        #plt.figure(figsize=(3,3))
        #plt.imshow(a1,cmap='hot')
        #plt.colorbar()
    for i in range(len(start)):
        print 'Frame nr. ', i, start[i]
        header = pyfits.getheader(start[i])
        a1 = flux(start[i],2*aperture1,RA_star,DEC_star)/float(header['EXPTIME'])
        print header['EXPTIME']
        if a1 > 0:
            #print a1
            star_flu.append(a1), star_AIRMASS.append(header['AIRMASS']*AIR_EXTINCTION), star_EXPTIME.append(header['EXPTIME'])
        else:
            star_flu.append(float('nan')), star_AIRMASS.append(float('nan')), star_EXPTIME.append(header['EXPTIME'])
        #plt.figure(figsize=(3,3))
        #plt.imshow(a1,cmap='hot')
        #plt.colorbar()
    com_flu = np.array(com_flu)
    print com_flu
    com_AIRMASS = np.array(com_AIRMASS)
    com_EXPTIME = np.array(com_EXPTIME)
    star_flu = np.array(star_flu)
    print star_flu
    star_AIRMASS = np.array(star_AIRMASS)
    star_EXPTIME = np.array(star_EXPTIME)
    com_flu = com_flu#/com_EXPTIME
    star_flu = star_flu#/star_EXPTIME
    com_flux = np.nanmean(com_flu)
    com_AIRMASS_num = np.nanmean(com_AIRMASS)
    star_AIRMASS_num = np.nanmean(star_AIRMASS)
    print star_AIRMASS_num
    mag1 = (star_AIRMASS_num-com_AIRMASS_num) + mag_com - 2.5*np.log10(star_flu/com_flux)
    mag = mag1
    print (star_AIRMASS_num-com_AIRMASS_num)
    print mag_com, com_flux, np.average(com_flu)
    print mag
    return mag

In [16]:
com1_1 = findmag(QUASAR1_g,refsta1_g,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_g,k_g)
com2_1 = findmag(QUASAR1_g,refsta1_g,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_g,k_g)
com3_1 = findmag(QUASAR1_g,refsta1_g,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_g,k_g)

com1_2 = findmag(QUASAR2_g,refsta2_g,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_g,k_g)
com2_2 = findmag(QUASAR2_g,refsta2_g,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_g,k_g)
com3_2 = findmag(QUASAR2_g,refsta2_g,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_g,k_g)

13.291
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/g/IMG2017292URh017.fits
INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the C

/home/lynge/anaconda2/lib/python2.7/site-packages/pyfits/hdu/image.py:515: VerifyWarning: Invalid 'BLANK' keyword in header.  The 'BLANK' keyword is only applicable to integer data, and will be ignored in this HDU.
  warnings.warn(msg, VerifyWarning)
the RADECSYS keyword is deprecated, use RADESYSa. [astropy.wcs.wcs]
No handlers could be found for logger "sewpy.sewpy"


INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
INFO: 
             

/home/lynge/anaconda2/lib/python2.7/site-packages/astropy/wcs/wcs.py:1669: RuntimeWarning: All-NaN slice encountered
  while (np.nanmax(dn) >= tol2 and k < maxiter):


60.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/g/IMG2017292URs093.fits
60.0
[3311.0125 3362.37   3436.2175 3412.1075 3388.4955 3391.6305 3398.88
 3390.846 ]
[nan nan nan]
nan
nan
13.291 3386.4449375000004 3386.4449375000004
[nan nan nan]
11.689
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URh002.fits


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:50: RuntimeWarning: Mean of empty slice


40.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URh003.fits
40.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URh006.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URh007.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URs004.fits
20.0
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URs005.fits
20.0
nan
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URs008.fits
20.0
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URs009.fits
20.0
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/IMG2017329URs026.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/IMG2017329URs027.fits
60.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/IMG2017329URs028.fits
60.0
[12140.58

In [17]:
print 'g-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

g-filter
Star 1
[14.61420499 14.60290622 14.60793794] [14.14261088 14.16234978 14.16596446]
14.38266237912047 0.22582764766097804
Star 2
[14.74099558 14.73424311 14.73655173] [14.28605632 14.28227313 14.29646829]
14.512764695267123 0.22454763782563408
Star 3
[nan nan nan] [nan nan nan]
nan nan


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: Mean of empty slice
  if sys.path[0] == '':
/home/lynge/anaconda2/lib/python2.7/site-packages/numpy/lib/nanfunctions.py:1434: RuntimeWarning: Degrees of freedom <= 0 for slice.
  keepdims=keepdims)


In [18]:
com1_1 = findmag(QUASAR1_r,refsta1_r,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_r,k_r)
com2_1 = findmag(QUASAR1_r,refsta1_r,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_r,k_r)
com3_1 = findmag(QUASAR1_r,refsta1_r,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_r,k_r)

com1_2 = findmag(QUASAR2_r,refsta2_r,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_r,k_r)
com2_2 = findmag(QUASAR2_r,refsta2_r,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_r,k_r)
com3_2 = findmag(QUASAR2_r,refsta2_r,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_r,k_r)

12.843
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh017.fits
40.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh018.fits
40.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh021.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh022.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs019.fits
20.0
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs020.fits
20.0
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs023.fits
20.0
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs024.fits
20.0
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/IMG2017292BRs091.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/IMG2017292BRs092.fits
60.0
Frame nr.  2 /media/lynge/Lyn

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:50: RuntimeWarning: Mean of empty slice


40.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRh003.fits
40.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRh006.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRh007.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRs004.fits
20.0
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRs005.fits
20.0
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRs008.fits
20.0
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/IMG2017329BRs009.fits
20.0
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/r/IMG2017329BRs026.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/r/IMG2017329BRs027.fits
60.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/r/IMG2017329BRs028.fits
60.0
[16500.5475 1

In [19]:
print 'r-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

r-filter
Star 1
[13.55068118 13.54913878 13.53827969] [13.22382652 13.23273844 13.21861821]
13.385547135835859 0.16058644393404609
Star 2
[13.95320224 13.94902438 13.94540393] [13.62064391 13.63212141 13.6178271 ]
13.786370493420142 0.16291393867822507
Star 3
[nan nan nan] [nan nan nan]
nan nan


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: Mean of empty slice
  if sys.path[0] == '':


In [20]:
com1_1 = findmag(QUASAR1_i,refsta1_i,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_i,k_i)
com2_1 = findmag(QUASAR1_i,refsta1_i,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_i,k_i)
com3_1 = findmag(QUASAR1_i,refsta1_i,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_i,k_i)

com1_2 = findmag(QUASAR2_i,refsta2_i,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_i,k_i)
com2_2 = findmag(QUASAR2_i,refsta2_i,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_i,k_i)
com3_2 = findmag(QUASAR2_i,refsta2_i,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_i,k_i)

12.668
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh017.fits
40.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh018.fits
40.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh021.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh022.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs019.fits
20.0
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs020.fits
20.0
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs023.fits
20.0
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs024.fits
20.0
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/IMG2017292ULs091.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/IMG2017292ULs092.fits
60.0
Frame nr.  2 /media/lynge/Lyn

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:50: RuntimeWarning: Mean of empty slice


40.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULh003.fits
40.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULh006.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULh007.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULs004.fits
20.0
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULs005.fits
20.0
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULs008.fits
20.0
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/IMG2017329ULs009.fits
20.0
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/i/IMG2017329ULs026.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/i/IMG2017329ULs027.fits
60.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/i/IMG2017329ULs028.fits
60.0
[10230.93   1

In [21]:
print 'i-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

i-filter
Star 1
[12.96798474 12.96357605 12.94759768] [12.76412003 12.76626866 12.75622011]
12.860961211032619 0.09899942059870484
Star 2
[13.51502679 13.49769404 13.5048947 ] [13.36429331 13.37459371 13.37562652]
13.43868817655929 0.06746857177959263
Star 3
[nan nan nan] [nan nan nan]
nan nan


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: Mean of empty slice
  if sys.path[0] == '':


In [22]:
com1_1 = findmag(QUASAR1_z,refsta1_z,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_z,k_z)
com2_1 = findmag(QUASAR1_z,refsta1_z,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_z,k_z)
com3_1 = findmag(QUASAR1_z,refsta1_z,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_z,k_z)

com1_2 = findmag(QUASAR2_z,refsta2_z,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_z,k_z)
com2_2 = findmag(QUASAR2_z,refsta2_z,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_z,k_z)
com3_2 = findmag(QUASAR2_z,refsta2_z,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_z,k_z)

12.593
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh017.fits
40.0
nan
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh018.fits
40.0
nan
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh021.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh022.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs019.fits
20.0
nan
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs020.fits
20.0
nan
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs023.fits
20.0
nan
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs024.fits
20.0
nan
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/IMG2017292BLs091.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/IMG2017292BLs092.fits
60.0
Frame

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:50: RuntimeWarning: Mean of empty slice


40.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLh003.fits
40.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLh006.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLh007.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLs004.fits
20.0
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLs005.fits
20.0
nan
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLs008.fits
20.0
nan
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/IMG2017329BLs009.fits
20.0
nan
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/IMG2017329BLs026.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/IMG2017329BLs027.fits
60.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/IMG2017329BLs028.fits
60.0
[

In [23]:
print 'z-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

z-filter
Star 1
[12.7467598  12.73736342 12.72854724] [12.5814219  12.55106073 12.55171988]
12.649478826466643 0.088801069693992
Star 2
[13.3655243  13.39600977 13.35741418] [13.10347347 13.12183399 13.13976805]
13.2473372920727 0.12662781192073505
Star 3
[nan nan nan] [nan nan nan]
nan nan


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:12: RuntimeWarning: Mean of empty slice
  if sys.path[0] == '':
