In [21]:
import numpy as np
import scipy as sp
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.colors import LogNorm
import scipy.stats as stats
from matplotlib import gridspec
import aplpy as apl #The Astronomy Plotting Library for python
import astropy
from astropy.stats import sigma_clip
from astropy.modeling import functional_models, models, fitting
import astropy.units as U
from astropy.coordinates import ICRS, Galactic, FK4, FK5, Angle, Latitude, Longitude
import astropy.constants as C
from astropy import wcs
import astropy.io.fits as fits
from astropy.io import ascii
import astropy.coordinates as coord
from astropy.coordinates import SkyCoord
from astropy.stats import signal_to_noise_oir_ccd as SNRas
#import spectral_cube as SC
#from spectral_cube import SpectralCube as sc
from astropy.wcs import WCS
matplotlib.use('Agg')
import matplotlib.cm as cm
#import astrometry as ast
import pyfits
import requests
import json
import os
from sklearn import datasets, linear_model
from scipy.optimize import curve_fit
import numpy.ma as ma
from astropy.table import Table, Column
import pyextract
import sewpy
import pandas as pd
from astropy import units as u

In [41]:
sta1_RA_WORLD = SkyCoord('18:45:08.692 -62:22:19.00', unit=(u.hourangle, u.deg)).ra.degree #UCAC3 86-422902
sta1_DEC_WORLD = SkyCoord('18:45:08.692 -62:22:19.00', unit=(u.hourangle, u.deg)).dec.degree

sta2_RA_WORLD = float('nan') #SkyCoord('18:45:03.00000 -67:23:25.0000', unit=(u.hourangle, u.deg)).ra.degree #TYC 8438-1960-1
sta2_DEC_WORLD = float('nan') #SkyCoord('18:45:03.00000 -67:23:25.0000', unit=(u.hourangle, u.deg)).dec.degree

sta3_RA_WORLD = SkyCoord('18:44:36.00000 -62:24:03.0000', unit=(u.hourangle, u.deg)).ra.degree #TYC 8438-1960-1
sta3_DEC_WORLD = SkyCoord('18:44:36.00000 -62:24:03.0000', unit=(u.hourangle, u.deg)).dec.degree

sky_RA_WORLD = SkyCoord('18:45:10 -62:22:42', unit=(u.hourangle, u.deg)).ra.degree #Random patch of sky
sky_DEC_WORLD = SkyCoord('18:45:10 -62:22:42', unit=(u.hourangle, u.deg)).dec.degree

k_g = 0.16
k_r = 0.08
k_i = 0.02
k_z = 0.01

mag_refsta1_g = 13.291
mag_refsta1_r = 12.843
mag_refsta1_i = 12.668
mag_refsta1_z = 12.593

mag_refsta2_g = 11.689
mag_refsta2_r = 11.491
mag_refsta2_i = 11.465
mag_refsta2_z = 11.500

refsta1_RA = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).ra.degree #P525_E_21_10_17
refsta1_DEC = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).dec.degree 

refsta2_RA = SkyCoord('00:55:09.9097 +00:43:12.906', unit=(u.hourangle, u.deg)).ra.degree #SA092_342_27_11_17
refsta2_DEC = SkyCoord('00:55:09.9097 +00:43:12.906', unit=(u.hourangle, u.deg)).dec.degree 

In [23]:
QUASAR1_g = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/g/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/g/')]

QUASAR2_g = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/')]

refsta1_g = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/g/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/g/')]

refsta2_g = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/')]

In [24]:
QUASAR1_r = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/')]

QUASAR2_r = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/r/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/r/')]

refsta1_r = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/')]

refsta2_r = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/r/')]

In [25]:
QUASAR1_i = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/')]

QUASAR2_i = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/i/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/i/')]

refsta1_i = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/')]

refsta2_i = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/i/')]

In [26]:
QUASAR1_z = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/')]

QUASAR2_z = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/')]

refsta1_z = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/')]

refsta2_z = [os.path.join('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/',f) \
        for f in os.listdir('/media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/z/')]

print QUASAR2_z

['/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/IMG2017329BLs026.fits', '/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/IMG2017329BLs027.fits', '/media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/z/IMG2017329BLs028.fits']


In [27]:
def dist(mid,end):
    return np.sqrt((mid[0] - end[0])**2 + (mid[1] - end[1])**2)

In [28]:
def flux_cal(A_mag,B_mag,B_flux):
    '''Flux of A found through magnitude and flux of B'''
    return B_flux*10**((B_mag-A_mag)/2.5)

In [29]:
def Basic(quasar,header):
    '''Provides a basic list of neccesities from the fits header file for use in the later \
    flux determination, it does not serve an individual purpose beyound that'''
    AGNdata = quasar #np.rot90(np.rot90(np.fliplr(quasar)))
    #header = data[0].header
    #print header
    RAstd = header['CRVAL1']
    DECstd = header['CRVAL2']
    #print RAstd, DECstd
    pixspa = header['PIXSCALE']/(3600.)
    #print pixspa
    RAstdpix = header['CRPIX1']
    DECstdpix = header['CRPIX2']
    exptime = 10 # header['EXPTIME']
    return header,AGNdata,RAstd,DECstd,pixspa,RAstdpix,DECstdpix,exptime

In [30]:
def curve(quasar,header,w,center,apparature):
    '''Determines the FLUX of the stellar object given the the numpy array of the image, \
    the header of the fits file, the astropy coordinate representation, \
    the object position and the apparature of interest'''
    header,AGNdata,RAstd,DECstd,pixspa,RAstdpix,DECstdpix,exptime = Basic(quasar,header)
    #AGNdata = np.swapaxes(AGNdata,0,1)
    y, x = np.ogrid[0:header['NAXIS1'],0:header['NAXIS1']]
    #w = np.swapaxes(w,0,1)
    #F_AGN = np.zeros((512,512,3)) #((int(2*apparature/pixspa)+1,int(2*apparature/pixspa)+1,3))
    #print center
    x1 = w.all_world2pix(center[0],center[1],0)
    x1,y1 = (x1[0]),(x1[1])
    try:
        mask = ((y-y1)**2 + (x-x1)**2) > (apparature/float(pixspa))**2
        AGNdata[mask] = float(0)
        mask = AGNdata == 0.
        rows = np.flatnonzero((~mask).sum(axis=1))
        cols = np.flatnonzero((~mask).sum(axis=0))
        AGNdata = AGNdata[rows.min():rows.max()+1, cols.min():cols.max()+1]
        #print apparature/float(pixspa)
    except:
        AGNdata = np.array([[float('nan'),float('nan')],[float('nan'),float('nan')]])
    #if np.sum(AGNdata) < 500:
    #    AGNdata = np.array([[float('nan'),float('nan')],[float('nan'),float('nan')]])
    return AGNdata/float(exptime), x1, y1


In [31]:
def comp1(qua,sta):
    '''Code to determine the relation between the AGN and the Stellar flux as determined by either me \
    or by the SExtractor program respectively'''
    comp = qua/sta
    return comp

In [32]:
def SNR(data1,data2,header,ap1,ap2):
    npix1 = np.pi*ap1**2/((header['PIXSCALE']/3600.)**2)
    npix2 = np.pi*ap2**2/((header['PIXSCALE']/3600.)**2)
    #data2_1 = ((data2-data1)/npix2)*npix1
    data1_2 = data1/10.
    data2_2 = data2/10.
    return SNRas(10.,data1_2,abs(data2_2),0,header['RON'],npix1,gain=header['GAIN'])

In [33]:
def SXtable(quas,aperture):
    header = pyfits.getheader(quas)
    phot_app = aperture*3600/header['PIXSCALE']
    np.set_printoptions(threshold=np.inf)
    sew = sewpy.SEW(params=['XMODEL_WORLD', 'YMODEL_WORLD', 'X2MODEL_WORLD', 'Y2MODEL_WORLD', 
                            'XMODEL_IMAGE', 'YMODEL_IMAGE', 'FLUX_RADIUS(1)', 'FLUX_APER','ELLIPTICITY'],
                    config={"DETECT_THRESH":10, 'DETECT_MINAREA':20, 'DETECT_MAXAREA':30000, 
                            "PHOT_FLUXFRAC":"0.5", 'PHOT_APERTURES':2*phot_app, 
                            'PIXEL_SCALE':header['PIXSCALE']}
                    , sexpath='/usr/bin/sextractor')
    out = sew(quas)
    return out

In [34]:
def flux(quas,aperture,main_RA_WORLD,main_DEC_WORLD):
    header = pyfits.getheader(quas)
    RAmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,1)[0]
    DECmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,1)[1]
    output = float('nan')
    if 15 < RAmain < header['NAXIS1'] - 15 and 15 < DECmain < header['NAXIS2'] - 15: 
        out = SXtable(quas,aperture)
        #print out['table']['XMODEL_IMAGE']
        #print RAmain
        RAmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,0)[0]
        DECmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,0)[1]
        #print out['table']['XMODEL_IMAGE'], out['table']['YMODEL_IMAGE']
        #print RAmain, DECmain

        for j in range(len(out['table']['XMODEL_IMAGE'])):
            #output['time'][i] = header['MJD-OBS']
            if RAmain - 20. < out['table']['XMODEL_IMAGE'][j] <  RAmain + 20. and \
            DECmain - 20. < out['table']['YMODEL_IMAGE'][j] < DECmain + 20.:
                #print 'YES'
                output = out['table']['FLUX_APER'][j]
                break
    else:
        output = float('nan')
        #print 'Done'
    return output


In [35]:
def findmag(start,compare1,RA_star,DEC_star,RA_com,DEC_com,mag_com,AIR_EXTINCTION):
    print mag_com
    aperture1 = 0.001
    #201.5441,-8.8601
    com_flu = []
    com_AIRMASS = []
    com_EXPTIME = []
    star_flu = []
    star_AIRMASS = []
    star_EXPTIME = []
    for i in range(len(compare1)):
        print 'Frame nr. ', i, compare1[i]
        header = pyfits.getheader(compare1[i])
        a1 = flux(compare1[i],2*aperture1,RA_com,DEC_com)/float(header['EXPTIME'])
        print header['EXPTIME']
        if a1 > 0:
            #print a1
            com_flu.append(a1), com_AIRMASS.append(header['AIRMASS']*AIR_EXTINCTION), com_EXPTIME.append(header['EXPTIME'])
        else:
            print a1
            com_flu.append(float('nan')), com_AIRMASS.append(float('nan')), com_EXPTIME.append(header['EXPTIME'])
        #plt.figure(figsize=(3,3))
        #plt.imshow(a1,cmap='hot')
        #plt.colorbar()
    for i in range(len(start)):
        print 'Frame nr. ', i, start[i]
        header = pyfits.getheader(start[i])
        a1 = flux(start[i],2*aperture1,RA_star,DEC_star)/float(header['EXPTIME'])
        print header['EXPTIME']
        if a1 > 0:
            #print a1
            star_flu.append(a1), star_AIRMASS.append(header['AIRMASS']*AIR_EXTINCTION), star_EXPTIME.append(header['EXPTIME'])
        else:
            star_flu.append(float('nan')), star_AIRMASS.append(float('nan')), star_EXPTIME.append(header['EXPTIME'])
        #plt.figure(figsize=(3,3))
        #plt.imshow(a1,cmap='hot')
        #plt.colorbar()
    com_flu = np.array(com_flu)
    print com_flu
    com_AIRMASS = np.array(com_AIRMASS)
    com_EXPTIME = np.array(com_EXPTIME)
    star_flu = np.array(star_flu)
    print star_flu
    star_AIRMASS = np.array(star_AIRMASS)
    star_EXPTIME = np.array(star_EXPTIME)
    com_flu = com_flu#/com_EXPTIME
    star_flu = star_flu#/star_EXPTIME
    com_flux = np.nanmean(com_flu)
    com_AIRMASS_num = np.nanmean(com_AIRMASS)
    star_AIRMASS_num = np.nanmean(star_AIRMASS)
    print star_AIRMASS_num
    mag1 = (star_AIRMASS_num-com_AIRMASS_num) + mag_com - 2.5*np.log10(star_flu/com_flux)
    mag = mag1
    print (star_AIRMASS_num-com_AIRMASS_num)
    print mag_com, com_flux, np.average(com_flu)
    print mag
    return mag

In [36]:
com1_1 = findmag(QUASAR1_g,refsta1_g,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_g,k_g)
com2_1 = findmag(QUASAR1_g,refsta1_g,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_g,k_g)
com3_1 = findmag(QUASAR1_g,refsta1_g,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_g,k_g)

com1_2 = findmag(QUASAR2_g,refsta2_g,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_g,k_g)
com2_2 = findmag(QUASAR2_g,refsta2_g,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_g,k_g)
com3_2 = findmag(QUASAR2_g,refsta2_g,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_g,k_g)

13.291
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/g/IMG2017292URh017.fits
INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the C

INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
INFO: 
             

INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
INFO: 
             

60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/g/IMG2017292URs092.fits
60.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/g/IMG2017292URs093.fits
60.0
[ 3311.0125  3362.37    3436.2175  3412.1075  3388.4955  3391.6305  3398.88
  3390.846 ]
[ 1339.21166667  1353.221       1346.96416667]
0.587456
0.315968
13.291 3386.4449375 3386.4449375
[ 14.61420499  14.60290622  14.60793794]
13.291
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/g/IMG2017292URh017.fits
INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from

INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
INFO: 
             

INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
INFO: 
             

60.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/g/IMG2017292URs093.fits
60.0
[ 3311.0125  3362.37    3436.2175  3412.1075  3388.4955  3391.6305  3398.88
  3390.846 ]
[ nan  nan  nan]
nan
nan
13.291 3386.4449375 3386.4449375
[ nan  nan  nan]
13.291
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/g/IMG2017292URh017.fits
INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distort

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:50: RuntimeWarning: Mean of empty slice


INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
INFO: 
             

INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
INFO: 
             

INFO: 
                Inconsistent SIP distortion information is present in the FITS header and the WCS object:
                SIP coefficients were detected, but CTYPE is missing a "-SIP" suffix.
                astropy.wcs is using the SIP distortion coefficients,
                therefore the coordinates calculated here might be incorrect.

                If you do not want to apply the SIP distortion coefficients,
                please remove the SIP coefficients from the FITS header or the
                WCS object.  As an example, if the image is already distortion-corrected
                (e.g., drizzled) then distortion components should not apply and the SIP
                coefficients should be removed.

                While the SIP distortion coefficients are being applied here, if that was indeed the intent,
                for consistency please append "-SIP" to the CTYPE in the FITS header or the WCS object.

                 [astropy.wcs.wcs]
INFO: 
             

40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URs004.fits
20.0
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URs005.fits
20.0
nan
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URs008.fits
20.0
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URs009.fits
20.0
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/IMG2017329URs026.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/IMG2017329URs027.fits
60.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/27-11-17-F51/g/IMG2017329URs028.fits
60.0
[ 12140.58    12107.75    12147.695   12114.2025  12294.905          nan
  12188.8     12153.42  ]
[ nan  nan  nan]
nan
nan
11.689 12163.9075 nan
[ nan  nan  nan]
11.689
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/27-11-17-SA092_342/g/IMG2017329URh002.fits
40.0
Frame nr.  1 /media/lynge/Lynge-Back-up

In [37]:
print 'g-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

g-filter
Star 1
[ 14.61420499  14.60290622  14.60793794] [ 14.14261088  14.16234978  14.16596446]
14.3826623791 0.225827647661
Star 2
[ nan  nan  nan] [ nan  nan  nan]
nan nan
Star 3
[ 14.01666471  14.02232238  14.0232699 ] [ 13.44284159  13.44114998  13.44021085]
13.7310765689 0.28968412367


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: Mean of empty slice
  


In [38]:
com1_1 = findmag(QUASAR1_r,refsta1_r,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_r,k_r)
com2_1 = findmag(QUASAR1_r,refsta1_r,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_r,k_r)
com3_1 = findmag(QUASAR1_r,refsta1_r,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_r,k_r)

com1_2 = findmag(QUASAR2_r,refsta2_r,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_r,k_r)
com2_2 = findmag(QUASAR2_r,refsta2_r,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_r,k_r)
com3_2 = findmag(QUASAR2_r,refsta2_r,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_r,k_r)

12.843
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh017.fits
40.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh018.fits
40.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh021.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh022.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs019.fits
20.0
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs020.fits
20.0
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs023.fits
20.0
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs024.fits
20.0
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/IMG2017292BRs091.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/IMG2017292BRs092.fits
60.0
Frame nr.  2 /media/lynge/Lyn

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:50: RuntimeWarning: Mean of empty slice


40.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh018.fits
40.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh021.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRh022.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs019.fits
20.0
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs020.fits
20.0
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs023.fits
20.0
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/r/IMG2017292BRs024.fits
20.0
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/IMG2017292BRs091.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/IMG2017292BRs092.fits
60.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/r/IMG2017292BRs093.fits
60.0
[ 5603.14    5630.8775  5680.31   

In [39]:
print 'r-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

r-filter
Star 1
[ 13.55068118  13.54913878  13.53827969] [ 13.22382652  13.23273844  13.21861821]
13.3855471358 0.160586443934
Star 2
[ nan  nan  nan] [ nan  nan  nan]
nan nan
Star 3
[ 13.14312554  13.13335145  13.14346401] [ 12.84886714  12.84653544  12.84877929]
12.9940204795 0.145999508386


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: Mean of empty slice
  


In [42]:
com1_1 = findmag(QUASAR1_i,refsta1_i,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_i,k_i)
com2_1 = findmag(QUASAR1_i,refsta1_i,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_i,k_i)
com3_1 = findmag(QUASAR1_i,refsta1_i,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_i,k_i)

com1_2 = findmag(QUASAR2_i,refsta2_i,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_i,k_i)
com2_2 = findmag(QUASAR2_i,refsta2_i,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_i,k_i)
com3_2 = findmag(QUASAR2_i,refsta2_i,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_i,k_i)

12.668
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh017.fits
40.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh018.fits
40.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh021.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh022.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs019.fits
20.0
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs020.fits
20.0
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs023.fits
20.0
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs024.fits
20.0
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/IMG2017292ULs091.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/IMG2017292ULs092.fits
60.0
Frame nr.  2 /media/lynge/Lyn

/home/lynge/.local/lib/python2.7/site-packages/astropy/wcs/wcs.py:1669: RuntimeWarning: All-NaN slice encountered
  while (np.nanmax(dn) >= tol2 and k < maxiter):


60.0
[ 3725.1575  3765.1075  3739.2675  3759.4875  3802.0025  3771.5425
  3758.812   3795.1775]
[ nan  nan  nan]
nan
nan
12.668 3764.5693125 3764.5693125
[ nan  nan  nan]
12.668
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh017.fits


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:50: RuntimeWarning: Mean of empty slice


40.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh018.fits
40.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh021.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULh022.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs019.fits
20.0
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs020.fits
20.0
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs023.fits
20.0
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/i/IMG2017292ULs024.fits
20.0
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/IMG2017292ULs091.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/IMG2017292ULs092.fits
60.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/i/IMG2017292ULs093.fits
60.0
[ 3725.1575  3765.1075  3739.2675 

In [43]:
print 'i-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

i-filter
Star 1
[ 12.96798474  12.96357605  12.94759768] [ 12.76412003  12.76626866  12.75622011]
12.860961211 0.0989994205987
Star 2
[ nan  nan  nan] [ nan  nan  nan]
nan nan
Star 3
[ 12.80376338  12.78654692  12.79253094] [ 12.72599533  12.72768299  12.73146365]
12.7613305371 0.0333732491887


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: Mean of empty slice
  


In [44]:
com1_1 = findmag(QUASAR1_z,refsta1_z,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_z,k_z)
com2_1 = findmag(QUASAR1_z,refsta1_z,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_z,k_z)
com3_1 = findmag(QUASAR1_z,refsta1_z,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_z,k_z)

com1_2 = findmag(QUASAR2_z,refsta2_z,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_z,k_z)
com2_2 = findmag(QUASAR2_z,refsta2_z,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_z,k_z)
com3_2 = findmag(QUASAR2_z,refsta2_z,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_z,k_z)

12.593
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh017.fits
40.0
nan
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh018.fits
40.0
nan
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh021.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh022.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs019.fits
20.0
nan
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs020.fits
20.0
nan
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs023.fits
20.0
nan
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs024.fits
20.0
nan
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/IMG2017292BLs091.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/IMG2017292BLs092.fits
60.0
Frame

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:50: RuntimeWarning: Mean of empty slice


40.0
nan
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh018.fits
40.0
nan
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh021.fits
40.0
Frame nr.  3 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLh022.fits
40.0
Frame nr.  4 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs019.fits
20.0
nan
Frame nr.  5 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs020.fits
20.0
nan
Frame nr.  6 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs023.fits
20.0
nan
Frame nr.  7 /media/lynge/Lynge-Back-up/Calibration/21-10-17-P525-E/z/IMG2017292BLs024.fits
20.0
nan
Frame nr.  0 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/IMG2017292BLs091.fits
60.0
Frame nr.  1 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/IMG2017292BLs092.fits
60.0
Frame nr.  2 /media/lynge/Lynge-Back-up/Calibration/21-10-17-F51/z/IMG2017292BLs093.fits
60.0
[       na

In [45]:
print 'z-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

z-filter
Star 1
[ 12.7467598   12.73736342  12.72854724] [ 12.5814219   12.55106073  12.55171988]
12.6494788265 0.088801069694
Star 2
[ nan  nan  nan] [ nan  nan  nan]
nan nan
Star 3
[ 12.78196326  12.77252195  12.75401283] [ 12.48061921  12.47826263  12.44914662]
12.6194210841 0.150642975345


/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:8: RuntimeWarning: Mean of empty slice
  
