In [17]:
import numpy as np
import scipy as sp
import matplotlib
import matplotlib.pyplot as plt
%matplotlib inline
from matplotlib.colors import LogNorm
import scipy.stats as stats
from matplotlib import gridspec
import aplpy as apl #The Astronomy Plotting Library for python
import astropy
from astropy.stats import sigma_clip
from astropy.modeling import functional_models, models, fitting
import astropy.units as U
from astropy.coordinates import ICRS, Galactic, FK4, FK5, Angle, Latitude, Longitude
import astropy.constants as C
from astropy import wcs
import astropy.io.fits as fits
from astropy.io import ascii
import astropy.coordinates as coord
from astropy.coordinates import SkyCoord
from astropy.stats import signal_to_noise_oir_ccd as SNRas
#import spectral_cube as SC
#from spectral_cube import SpectralCube as sc
from astropy.wcs import WCS
matplotlib.use('Agg')
import matplotlib.cm as cm
#import astrometry as ast
import pyfits
import requests
import json
import os
from sklearn import datasets, linear_model
from scipy.optimize import curve_fit
import numpy.ma as ma
from astropy.table import Table, Column
import pyextract
import sewpy
import pandas as pd
from astropy import units as u

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:25: UserWarning: 
This call to matplotlib.use() has no effect because the backend has already
been chosen; matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.

The backend was *originally* set to 'module://ipykernel.pylab.backend_inline' by the following code:
  File "/home/lynge/anaconda2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/home/lynge/anaconda2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/lynge/anaconda2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 477,

In [18]:
sta1_RA_WORLD = SkyCoord('09:16:25.8 -62:24:20', unit=(u.hourangle, u.deg)).ra.degree 
sta1_DEC_WORLD = SkyCoord('09:16:25.8 -62:24:20', unit=(u.hourangle, u.deg)).dec.degree

sta2_RA_WORLD = SkyCoord('09:15:59 -62:19:41', unit=(u.hourangle, u.deg)).ra.degree
sta2_DEC_WORLD = SkyCoord('09:15:59 -62:19:41', unit=(u.hourangle, u.deg)).dec.degree

sta3_RA_WORLD = SkyCoord('09:16:24 -62:19:05', unit=(u.hourangle, u.deg)).ra.degree #TYC 8480-374-1
sta3_DEC_WORLD = SkyCoord('09:16:24 -62:19:05', unit=(u.hourangle, u.deg)).dec.degree

sky_RA_WORLD = SkyCoord('09:16:06 -62:19:18', unit=(u.hourangle, u.deg)).ra.degree #Random patch of sky
sky_DEC_WORLD = SkyCoord('09:16:06 -62:19:18', unit=(u.hourangle, u.deg)).dec.degree


k_g = 0.16
k_r = 0.08
k_i = 0.02
k_z = 0.01

mag_refsta1_g = 11.689
mag_refsta1_r = 11.491
mag_refsta1_i = 11.465
mag_refsta1_z = 11.500

mag_refsta2_g = 13.291
mag_refsta2_r = 12.843
mag_refsta2_i = 12.668
mag_refsta2_z = 12.593

refsta1_RA = SkyCoord('00:55:09.9097 +00:43:12.906', unit=(u.hourangle, u.deg)).ra.degree #SA092_342_27_11_17
refsta1_DEC = SkyCoord('00:55:09.9097 +00:43:12.906', unit=(u.hourangle, u.deg)).dec.degree 

refsta2_RA = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).ra.degree #PG1323_086_10_07_17
refsta2_DEC = SkyCoord('00:24:28 07:49:00', unit=(u.hourangle, u.deg)).dec.degree 

In [19]:
QUASAR1_g = [os.path.join('/media/lynge/LACIE/Calibration/27-11-17-IRAS09149/g/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/27-11-17-IRAS09149/g/')]

QUASAR2_g = [os.path.join('/media/lynge/LACIE/Calibration/21-10-17-IRAS09149/g/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/21-10-17-IRAS09149/g/')]

refsta1_g = [os.path.join('/media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/')]

refsta2_g = [os.path.join('/media/lynge/LACIE/Calibration/21-10-17-P525-E/g/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/21-10-17-P525-E/g/')]

In [20]:
QUASAR1_r = [os.path.join('/media/lynge/LACIE/Calibration/27-11-17-IRAS09149/r/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/27-11-17-IRAS09149/r/')]

QUASAR2_r = [os.path.join('/media/lynge/LACIE/Calibration/21-10-17-IRAS09149/r/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/21-10-17-IRAS09149/r/')]

refsta1_r = [os.path.join('/media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/')]

refsta2_r = [os.path.join('/media/lynge/LACIE/Calibration/21-10-17-P525-E/r/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/21-10-17-P525-E/r/')]

In [21]:
QUASAR1_i = [os.path.join('/media/lynge/LACIE/Calibration/27-11-17-IRAS09149/i/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/27-11-17-IRAS09149/i/')]

QUASAR2_i = [os.path.join('/media/lynge/LACIE/Calibration/21-10-17-IRAS09149/i/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/21-10-17-IRAS09149/i/')]

refsta1_i = [os.path.join('/media/lynge/LACIE/Calibration/27-11-17-SA092_342/i/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/27-11-17-SA092_342/i/')]

refsta2_i = [os.path.join('/media/lynge/LACIE/Calibration/21-10-17-P525-E/i/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/21-10-17-P525-E/i/')]

In [22]:
QUASAR1_z = [os.path.join('/media/lynge/LACIE/Calibration/27-11-17-IRAS09149/z/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/27-11-17-IRAS09149/z/')]

QUASAR2_z = [os.path.join('/media/lynge/LACIE/Calibration/21-10-17-IRAS09149/z/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/21-10-17-IRAS09149/z/')]

refsta1_z = [os.path.join('/media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/')]

refsta2_z = [os.path.join('/media/lynge/LACIE/Calibration/21-10-17-P525-E/z/',f) \
        for f in os.listdir('/media/lynge/LACIE/Calibration/21-10-17-P525-E/z/')]

In [23]:
def dist(mid,end):
    return np.sqrt((mid[0] - end[0])**2 + (mid[1] - end[1])**2)

In [24]:
def flux_cal(A_mag,B_mag,B_flux):
    '''Flux of A found through magnitude and flux of B'''
    return B_flux*10**((B_mag-A_mag)/2.5)

In [25]:
def Basic(quasar,header):
    '''Provides a basic list of neccesities from the fits header file for use in the later \
    flux determination, it does not serve an individual purpose beyound that'''
    AGNdata = quasar #np.rot90(np.rot90(np.fliplr(quasar)))
    #header = data[0].header
    #print header
    RAstd = header['CRVAL1']
    DECstd = header['CRVAL2']
    #print RAstd, DECstd
    pixspa = header['PIXSCALE']/(3600.)
    #print pixspa
    RAstdpix = header['CRPIX1']
    DECstdpix = header['CRPIX2']
    exptime = 10 # header['EXPTIME']
    return header,AGNdata,RAstd,DECstd,pixspa,RAstdpix,DECstdpix,exptime

In [26]:
def curve(quasar,header,w,center,apparature):
    '''Determines the FLUX of the stellar object given the the numpy array of the image, \
    the header of the fits file, the astropy coordinate representation, \
    the object position and the apparature of interest'''
    header,AGNdata,RAstd,DECstd,pixspa,RAstdpix,DECstdpix,exptime = Basic(quasar,header)
    #AGNdata = np.swapaxes(AGNdata,0,1)
    y, x = np.ogrid[0:header['NAXIS1'],0:header['NAXIS1']]
    #w = np.swapaxes(w,0,1)
    #F_AGN = np.zeros((512,512,3)) #((int(2*apparature/pixspa)+1,int(2*apparature/pixspa)+1,3))
    #print center
    x1 = w.all_world2pix(center[0],center[1],0)
    x1,y1 = (x1[0]),(x1[1])
    try:
        mask = ((y-y1)**2 + (x-x1)**2) > (apparature/float(pixspa))**2
        AGNdata[mask] = float(0)
        mask = AGNdata == 0.
        rows = np.flatnonzero((~mask).sum(axis=1))
        cols = np.flatnonzero((~mask).sum(axis=0))
        AGNdata = AGNdata[rows.min():rows.max()+1, cols.min():cols.max()+1]
        #print apparature/float(pixspa)
    except:
        AGNdata = np.array([[float('nan'),float('nan')],[float('nan'),float('nan')]])
    #if np.sum(AGNdata) < 500:
    #    AGNdata = np.array([[float('nan'),float('nan')],[float('nan'),float('nan')]])
    return AGNdata/float(exptime), x1, y1


In [27]:
def comp1(qua,sta):
    '''Code to determine the relation between the AGN and the Stellar flux as determined by either me \
    or by the SExtractor program respectively'''
    comp = qua/sta
    return comp

In [28]:
def SNR(data1,data2,header,ap1,ap2):
    npix1 = np.pi*ap1**2/((header['PIXSCALE']/3600.)**2)
    npix2 = np.pi*ap2**2/((header['PIXSCALE']/3600.)**2)
    #data2_1 = ((data2-data1)/npix2)*npix1
    data1_2 = data1/10.
    data2_2 = data2/10.
    return SNRas(10.,data1_2,abs(data2_2),0,header['RON'],npix1,gain=header['GAIN'])

In [29]:
def SXtable(quas,aperture):
    header = pyfits.getheader(quas)
    phot_app = aperture*3600/header['PIXSCALE']
    np.set_printoptions(threshold=np.inf)
    sew = sewpy.SEW(params=['XMODEL_WORLD', 'YMODEL_WORLD', 'X2MODEL_WORLD', 'Y2MODEL_WORLD', 
                            'XMODEL_IMAGE', 'YMODEL_IMAGE', 'FLUX_RADIUS(1)', 'FLUX_APER','ELLIPTICITY'],
                    config={"DETECT_THRESH":5, 'DETECT_MINAREA':20, 'DETECT_MAXAREA':30000, 
                            "PHOT_FLUXFRAC":"0.5", 'PHOT_APERTURES':2*phot_app, 
                            'PIXEL_SCALE':header['PIXSCALE']}
                    , sexpath='/usr/bin/sextractor')
    out = sew(quas)
    return out

In [30]:
def flux(quas,aperture,main_RA_WORLD,main_DEC_WORLD):
    header = pyfits.getheader(quas)
    RAmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,1)[0]
    DECmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,1)[1]
    output = float('nan')
    if 15 < RAmain < header['NAXIS1'] - 15 and 15 < DECmain < header['NAXIS2'] - 15: 
        out = SXtable(quas,aperture)
        #print out['table']['XMODEL_IMAGE']
        #print RAmain
        RAmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,0)[0]
        DECmain = WCS(quas).all_world2pix(main_RA_WORLD,main_DEC_WORLD,0)[1]
        #print out['table']['XMODEL_IMAGE'], out['table']['YMODEL_IMAGE']
        #print RAmain, DECmain

        for j in range(len(out['table']['XMODEL_IMAGE'])):
            #output['time'][i] = header['MJD-OBS']
            if RAmain - 20. < out['table']['XMODEL_IMAGE'][j] <  RAmain + 20. and \
            DECmain - 20. < out['table']['YMODEL_IMAGE'][j] < DECmain + 20.:
                #print 'YES'
                output = out['table']['FLUX_APER'][j]
                break
    else:
        output = float('nan')
        #print 'Done'
    return output


In [31]:
def findmag(start,compare1,RA_star,DEC_star,RA_com,DEC_com,mag_com,AIR_EXTINCTION):
    print mag_com
    aperture1 = 0.0012
    #201.5441,-8.8601
    com_flu = []
    com_AIRMASS = []
    com_EXPTIME = []
    star_flu = []
    star_AIRMASS = []
    star_EXPTIME = []
    for i in range(len(compare1)):
        print 'Frame nr. ', i, compare1[i]
        header = pyfits.getheader(compare1[i])
        a1 = flux(compare1[i],2*aperture1,RA_com,DEC_com)/float(header['EXPTIME'])
        print header['EXPTIME']
        if a1 > 0:
            #print a1
            com_flu.append(a1), com_AIRMASS.append(header['AIRMASS']*AIR_EXTINCTION), com_EXPTIME.append(header['EXPTIME'])
        else:
            #print a1
            com_flu.append(float('nan')), com_AIRMASS.append(float('nan')), com_EXPTIME.append(header['EXPTIME'])
        #plt.figure(figsize=(3,3))
        #plt.imshow(a1,cmap='hot')
        #plt.colorbar()
    for i in range(len(start)):
        print 'Frame nr. ', i, start[i]
        header = pyfits.getheader(start[i])
        a1 = flux(start[i],2*aperture1,RA_star,DEC_star)/float(header['EXPTIME'])
        #print header['EXPTIME']
        if a1 > 0:
            #print a1
            star_flu.append(a1), star_AIRMASS.append(header['AIRMASS']*AIR_EXTINCTION), star_EXPTIME.append(header['EXPTIME'])
        else:
            star_flu.append(float('nan')), star_AIRMASS.append(float('nan')), star_EXPTIME.append(header['EXPTIME'])
        #plt.figure(figsize=(3,3))
        #plt.imshow(a1,cmap='hot')
        #plt.colorbar()
    com_flu = np.array(com_flu)
    #print com_flu
    com_AIRMASS = np.array(com_AIRMASS)
    com_EXPTIME = np.array(com_EXPTIME)
    star_flu = np.array(star_flu)
    #print star_flu
    star_AIRMASS = np.array(star_AIRMASS)
    star_EXPTIME = np.array(star_EXPTIME)
    com_flu = com_flu#/com_EXPTIME
    star_flu = star_flu#/star_EXPTIME
    com_flux = np.nanmean(com_flu)
    com_AIRMASS_num = np.nanmean(com_AIRMASS)
    star_AIRMASS_num = np.nanmean(star_AIRMASS)
    #print star_AIRMASS_num
    mag1 = (star_AIRMASS_num-com_AIRMASS_num) + mag_com - 2.5*np.log10(star_flu/com_flux)
    mag = mag1
    #print (star_AIRMASS_num-com_AIRMASS_num)
    #print mag_com, com_flux, np.average(com_flu)
    #print mag
    return mag

In [32]:
com1_1 = findmag(QUASAR1_g,refsta1_g,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_g,k_g)
com2_1 = findmag(QUASAR1_g,refsta1_g,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_g,k_g)
com3_1 = findmag(QUASAR1_g,refsta1_g,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_g,k_g)

com1_2 = findmag(QUASAR2_g,refsta2_g,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_g,k_g)
com2_2 = findmag(QUASAR2_g,refsta2_g,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_g,k_g)
com3_2 = findmag(QUASAR2_g,refsta2_g,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_g,k_g)

11.689
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URh002.fits
40.0
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URh003.fits
40.0
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URh006.fits
40.0
Frame nr.  3 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URh007.fits
40.0
Frame nr.  4 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URs004.fits
20.0
Frame nr.  5 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URs005.fits
20.0
Frame nr.  6 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URs008.fits
20.0
Frame nr.  7 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URs009.fits
20.0
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/g/IMG2017329URs072.fits
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/g/IMG2017329URs073.fits
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/g/IMG2017329URs071.f

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:50: RuntimeWarning: Mean of empty slice


11.689
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URh002.fits
40.0
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URh003.fits
40.0
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URh006.fits
40.0
Frame nr.  3 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URh007.fits
40.0
Frame nr.  4 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URs004.fits
20.0
Frame nr.  5 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URs005.fits
20.0
Frame nr.  6 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URs008.fits
20.0
Frame nr.  7 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/g/IMG2017329URs009.fits
20.0
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/g/IMG2017329URs072.fits
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/g/IMG2017329URs073.fits
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/g/IMG2017329URs071.f

In [33]:
print 'g-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

g-filter
Star 1
[nan nan nan] [12.5001929  12.49269364 12.50540277]
12.499429771414801 0.005216467820133632
Star 2
[14.85773805 14.83229475 14.85253201] [14.97184118 14.99778103 14.9961708 ]
14.918059637765461 0.0714580169040668
Star 3
[15.35997589 15.35773438 15.31922691] [15.45493664 15.48506766 15.46939431]
15.407722630648701 0.06406361626133218


In [34]:
com1_1 = findmag(QUASAR1_r,refsta1_r,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_r,k_r)
com2_1 = findmag(QUASAR1_r,refsta1_r,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_r,k_r)
com3_1 = findmag(QUASAR1_r,refsta1_r,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_r,k_r)

com1_2 = findmag(QUASAR2_r,refsta2_r,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_r,k_r)
com2_2 = findmag(QUASAR2_r,refsta2_r,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_r,k_r)
com3_2 = findmag(QUASAR2_r,refsta2_r,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_r,k_r)

11.491
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRh002.fits
40.0
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRh003.fits
40.0
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRh006.fits
40.0
Frame nr.  3 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRh007.fits
40.0
Frame nr.  4 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRs004.fits
20.0
Frame nr.  5 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRs005.fits
20.0
Frame nr.  6 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRs008.fits
20.0
Frame nr.  7 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRs009.fits
20.0
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/r/IMG2017329BRs072.fits
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/r/IMG2017329BRs073.fits
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/r/IMG2017329BRs071.f

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:50: RuntimeWarning: Mean of empty slice


11.491
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRh002.fits
40.0
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRh003.fits
40.0
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRh006.fits
40.0
Frame nr.  3 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRh007.fits
40.0
Frame nr.  4 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRs004.fits
20.0
Frame nr.  5 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRs005.fits
20.0
Frame nr.  6 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRs008.fits
20.0
Frame nr.  7 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/r/IMG2017329BRs009.fits
20.0
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/r/IMG2017329BRs072.fits
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/r/IMG2017329BRs073.fits
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/r/IMG2017329BRs071.f

In [35]:
print 'r-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

r-filter
Star 1
[nan nan nan] [11.78438249 11.78410143 11.79144869]
11.78664420448441 0.0033992189365341444
Star 2
[13.90444843 13.89534656 13.8978516 ] [14.03238153 14.05022412 14.03533056]
13.969263800253998 0.07031800443084336
Star 3
[14.41407449 14.42004549 14.40018377] [14.5717355  14.56927824 14.5768917 ]
14.492034863995775 0.08084586719688572


In [36]:
com1_1 = findmag(QUASAR1_i,refsta1_i,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_i,k_i)
com2_1 = findmag(QUASAR1_i,refsta1_i,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_i,k_i)
com3_1 = findmag(QUASAR1_i,refsta1_i,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_i,k_i)

com1_2 = findmag(QUASAR2_i,refsta2_i,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_i,k_i)
com2_2 = findmag(QUASAR2_i,refsta2_i,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_i,k_i)
com3_2 = findmag(QUASAR2_i,refsta2_i,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_i,k_i)

11.465
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/i/IMG2017329ULh002.fits
40.0
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/i/IMG2017329ULh003.fits
40.0
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/i/IMG2017329ULh006.fits
40.0
Frame nr.  3 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/i/IMG2017329ULh007.fits
40.0
Frame nr.  4 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/i/IMG2017329ULs004.fits
20.0
Frame nr.  5 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/i/IMG2017329ULs005.fits
20.0
Frame nr.  6 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/i/IMG2017329ULs008.fits
20.0
Frame nr.  7 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/i/IMG2017329ULs009.fits
20.0
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/i/IMG2017329ULs072.fits
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/i/IMG2017329ULs073.fits
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/i/IMG2017329ULs071.f

In [37]:
print 'i-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

i-filter
Star 1
[11.42420682 11.42381946 11.43602601] [11.35873531 11.35915789 11.36471376]
11.394443208129632 0.03386717552579026
Star 2
[13.47297888 13.48820214 13.49333364] [13.54602923 13.54391912 13.53693611]
13.513566520614448 0.02949949977179056
Star 3
[14.00395753 14.00336811 13.9993306 ] [14.05579466 14.05964467 14.07406228]
14.032692975513344 0.031011350628744622


In [38]:
com1_1 = findmag(QUASAR1_z,refsta1_z,sta1_RA_WORLD,sta1_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_z,k_z)
com2_1 = findmag(QUASAR1_z,refsta1_z,sta2_RA_WORLD,sta2_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_z,k_z)
com3_1 = findmag(QUASAR1_z,refsta1_z,sta3_RA_WORLD,sta3_DEC_WORLD,refsta1_RA,refsta1_DEC,mag_refsta1_z,k_z)

com1_2 = findmag(QUASAR2_z,refsta2_z,sta1_RA_WORLD,sta1_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_z,k_z)
com2_2 = findmag(QUASAR2_z,refsta2_z,sta2_RA_WORLD,sta2_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_z,k_z)
com3_2 = findmag(QUASAR2_z,refsta2_z,sta3_RA_WORLD,sta3_DEC_WORLD,refsta2_RA,refsta2_DEC,mag_refsta2_z,k_z)

11.5
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLh002.fits
40.0
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLh003.fits
40.0
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLh006.fits
40.0
Frame nr.  3 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLh007.fits
40.0
Frame nr.  4 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLs004.fits
20.0
Frame nr.  5 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLs005.fits
20.0
Frame nr.  6 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLs008.fits
20.0
Frame nr.  7 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLs009.fits
20.0
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/z/IMG2017329BLs072.fits
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/z/IMG2017329BLs073.fits
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/z/IMG2017329BLs071.fit

/home/lynge/anaconda2/lib/python2.7/site-packages/ipykernel_launcher.py:50: RuntimeWarning: Mean of empty slice


11.5
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLh002.fits
40.0
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLh003.fits
40.0
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLh006.fits
40.0
Frame nr.  3 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLh007.fits
40.0
Frame nr.  4 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLs004.fits
20.0
Frame nr.  5 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLs005.fits
20.0
Frame nr.  6 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLs008.fits
20.0
Frame nr.  7 /media/lynge/LACIE/Calibration/27-11-17-SA092_342/z/IMG2017329BLs009.fits
20.0
Frame nr.  0 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/z/IMG2017329BLs072.fits
Frame nr.  1 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/z/IMG2017329BLs073.fits
Frame nr.  2 /media/lynge/LACIE/Calibration/27-11-17-IRAS09149/z/IMG2017329BLs071.fit

In [39]:
print 'z-filter'
print 'Star 1'
print com1_1,com1_2
print np.nanmean((com1_1,com1_2)), np.nanstd((com1_1,com1_2))

print 'Star 2'
print com2_1,com2_2
print np.nanmean((com2_1,com2_2)), np.nanstd((com2_1,com2_2))

print 'Star 3'
print com3_1,com3_2
print np.nanmean((com3_1,com3_2)), np.nanstd((com3_1,com3_2))

z-filter
Star 1
[nan nan nan] [11.18274103 11.17941182 11.18113477]
11.181095876024264 0.0013594218719770004
Star 2
[13.24969126 13.21194272 13.24769823] [13.34326795 13.31246378 13.37060567]
13.289278268083047 0.056779421611579964
Star 3
[13.63372462 13.60423024 13.63363238] [13.76160574 13.87688149 13.7581553 ]
13.71137162661873 0.09631321965109683


In [40]:
HD101274_1 = findmag(NGC3783_r,P_r,sta1_RA_WORLD,sta1_DEC_WORLD,r_P_RA,r_P_DEC,P_mag_r,k_r)
Tyc_22_1 = findmag(NGC3783_r,P_r,sta2_RA_WORLD,sta2_DEC_WORLD,r_P_RA,r_P_DEC,P_mag_r,k_r)
Tyc_529_1 = findmag(NGC3783_r,P_r,sta3_RA_WORLD,sta3_DEC_WORLD,r_P_RA,r_P_DEC,P_mag_r,k_r)




NameError: name 'NGC3783_r' is not defined

In [ ]:
print 'r-filter'
print HD101274_1
print np.mean(HD101274_1,), np.std(HD101274_1)

print Tyc_22_1
print np.mean(Tyc_22_1), np.std(Tyc_22_1)

print Tyc_529_1
print np.mean(Tyc_529_1), np.std(Tyc_529_1)

In [ ]:
HD101274_1 = findmag(NGC3783_i,P_i,sta1_RA_WORLD,sta1_DEC_WORLD,i_P_RA,i_P_DEC,P_mag_i,k_i)
Tyc_22_1 = findmag(NGC3783_i,P_i,sta2_RA_WORLD,sta2_DEC_WORLD,i_P_RA,i_P_DEC,P_mag_i,k_i)
Tyc_529_1 = findmag(NGC3783_i,P_i,sta3_RA_WORLD,sta3_DEC_WORLD,i_P_RA,i_P_DEC,P_mag_i,k_i)




In [ ]:
print 'i-filter'
print HD101274_1
print np.mean(HD101274_1,), np.std(HD101274_1)

print Tyc_22_1
print np.mean(Tyc_22_1), np.std(Tyc_22_1)

print Tyc_529_1
print np.mean(Tyc_529_1), np.std(Tyc_529_1)

In [ ]:
sta2_RA_WORLD = 174.82083333
sta2_DEC_WORLD = -37.76194444

HD101274_1 = findmag(NGC3783_z,P_z,sta1_RA_WORLD,sta1_DEC_WORLD,z_P_RA,z_P_DEC,P_mag_z,k_z)
Tyc_22_1 = findmag(NGC3783_z,P_z,sta2_RA_WORLD,sta2_DEC_WORLD,z_P_RA,z_P_DEC,P_mag_z,k_z)
Tyc_529_1 = findmag(NGC3783_z,P_z,sta3_RA_WORLD,sta3_DEC_WORLD,z_P_RA,z_P_DEC,P_mag_z,k_z)




In [ ]:
print 'z-filter'
print HD101274_1
print np.nanmean(HD101274_1,), np.nanstd(HD101274_1)

print Tyc_22_1
print np.nanmean(Tyc_22_1), np.nanstd(Tyc_22_1)

print Tyc_529_1
print np.nanmean(Tyc_529_1), np.nanstd(Tyc_529_1)